### ISSUE TITLE
Uncaught Error: Assert failed: om-sync component not given url (not (nil? url))

### ISSUE THREAD

**Issue by shmish111** [bensu/om-intermediate-tut#3]
After getting to the end of this tutorial I have the above error.  To be sure, I copied and pasted `om-async.core`, did `lein clean` but I still get the error.  I couldn't find anyone else having this problem, what am I doing wrong?

**Comment by bensu** [comment]
Since you closed the issue, I'm assuming you've found the problem. Please reopen it if you are still having problems.

**Comment by shmish111** [comment]
Yes, my apologies just a tiny bug I had made. Nice tutorial :-)
